[package]
name = "chip-8-cpu"
version = "0.1.0"
authors = ["Dione <dionemorales@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
